# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_auto_20171120_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='objetives',
            field=models.ManyToManyField(blank=True, to='Proyectos.Objetive'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='obstacles',
            field=models.ManyToManyField(blank=True, to='Proyectos.Obstacle'),
        ),
    ]
