# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_auto_20171120_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetive',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
